// SQUARE BRACKETS = CORCHETES CUADRADOS
const listaAleatoriaDeElementos = ["Hola mundo", 23, [1.3, 1.4, 1.6], true, null]

// SI QUIERO ACCEDER AL VALOR DE UN ELEMENTO EN PARTICULAR,
// TENGO QUE ESCOGERLO DE ACUERDO A SU POSICION Y CON AYUDA
// DE LA "NOTACION DE CORCHETES CUADRADOS" O SQUARE BRACKET NOTATION
console.log(listaAleatoriaDeElementos[2]);